"""Insights page: rule-based business findings."""

from __future__ import annotations

import sqlite3

from PySide6.QtCore import Qt
from PySide6.QtGui import QColor, QFont
from PySide6.QtWidgets import (
    QListWidget,
    QListWidgetItem,
    QVBoxLayout,
    QWidget,
)

from src.insights.rules import Insight, Severity, generate_insights


_SEVERITY_COLORS = {
    Severity.RISK: QColor("#f8d7da"),
    Severity.WARNING: QColor("#fff3cd"),
    Severity.INFO: QColor("#e7f3ff"),
}


class InsightsPage(QWidget):
    """Business findings generated by the rule engine."""

    def __init__(self, conn: sqlite3.Connection) -> None:
        super().__init__()
        self._conn = conn

        layout = QVBoxLayout(self)
        layout.setContentsMargins(16, 16, 16, 16)

        self.list = QListWidget()
        self.list.setWordWrap(True)
        self.list.setSpacing(4)
        layout.addWidget(self.list)

    def refresh(self) -> None:
        self.list.clear()
        findings: list[Insight] = generate_insights(self._conn)
        for f in findings:
            item = QListWidgetItem()
            item.setText(f"{f.title}\n{f.detail}")
            font = QFont()
            font.setPointSize(11)
            item.setFont(font)
            color = _SEVERITY_COLORS.get(f.severity)
            if color is not None:
                item.setBackground(color)
            item.setFlags(Qt.ItemIsEnabled)
            self.list.addItem(item)