"""Excel report generation.

Produces a multi-sheet workbook with the shop's KPIs, top products,
revenue by period, geography, data quality issues, and insights.

All values come from the analytics and insights modules. This file
does not compute anything itself.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from src.analytics import reconciliation
from src.analytics.kpi import (
    compute_kpi,
    revenue_by_country,
    revenue_by_period,
    top_listings_by_revenue,
)
from src.database.repositories import issues_repo
from src.insights.rules import generate_insights


HEADER_FONT = Font(bold=True, color="FFFFFF")
HEADER_FILL = PatternFill("solid", fgColor="2F5496")
TITLE_FONT = Font(bold=True, size=14)
LABEL_FONT = Font(bold=True)


def _write_title(ws, cell: str, text: str) -> None:
    ws[cell] = text
    ws[cell].font = TITLE_FONT


def _write_table(
    ws,
    start_row: int,
    headers: list[str],
    rows: list[list],
) -> int:
    """Write a header row + data rows starting at start_row. Returns next free row."""
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=start_row, column=col_idx, value=header)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(horizontal="left", vertical="center")

    for r_idx, row in enumerate(rows, start=start_row + 1):
        for c_idx, value in enumerate(row, start=1):
            ws.cell(row=r_idx, column=c_idx, value=value)

    # Auto-size columns roughly based on content length.
    for col_idx in range(1, len(headers) + 1):
        max_len = len(str(headers[col_idx - 1]))
        for r_idx in range(start_row + 1, start_row + 1 + len(rows)):
            v = ws.cell(row=r_idx, column=col_idx).value
            if v is not None:
                max_len = max(max_len, len(str(v)))
        ws.column_dimensions[get_column_letter(col_idx)].width = min(max_len + 2, 50)

    return start_row + 1 + len(rows)


# ---------------------------------------------------------------
# Sheet builders
# ---------------------------------------------------------------

def _sheet_summary(wb: Workbook, conn: sqlite3.Connection) -> None:
    ws = wb.active
    ws.title = "Summary"

    kpi = compute_kpi(conn)

    _write_title(ws, "A1", "Etsy Business Report")
    ws["A2"] = "Generated by Etsy BI Analyzer"

    row = 4
    metrics = [
        ("Gross Revenue", kpi.gross_revenue, "$"),
        ("Fees", kpi.fees, "$"),
        ("Net Revenue", kpi.net_revenue, "$"),
        ("Refunds", kpi.refunds, "$"),
        ("Net after Refunds", kpi.net_after_refunds, "$"),
        ("Orders", kpi.orders_count, ""),
        ("Items Sold", kpi.items_sold, ""),
        ("Average Order Value", kpi.average_order_value, "$"),
        ("Average Item Value", kpi.average_item_value, "$"),
        ("Fee Ratio", kpi.fee_ratio, "%"),
        ("Refund Rate", kpi.refund_rate, "%"),
        ("Items per Order", kpi.items_per_order, ""),
    ]
    for label, value, kind in metrics:
        ws.cell(row=row, column=1, value=label).font = LABEL_FONT
        if kind == "$":
            ws.cell(row=row, column=2, value=round(value, 2)).number_format = "$#,##0.00"
        elif kind == "%":
            ws.cell(row=row, column=2, value=round(value, 4)).number_format = "0.0%"
        else:
            ws.cell(row=row, column=2, value=value)
        row += 1

    ws.column_dimensions["A"].width = 24
    ws.column_dimensions["B"].width = 18


def _sheet_sales(wb: Workbook, conn: sqlite3.Connection) -> None:
    ws = wb.create_sheet("Sales")
    _write_title(ws, "A1", "Revenue by Month")
    rows = revenue_by_period(conn, period="month")
    _write_table(
        ws,
        start_row=3,
        headers=["Period", "Revenue", "Orders"],
        rows=[[r["period"], round(r["revenue"], 2), r["orders"]] for r in rows],
    )


def _sheet_products(wb: Workbook, conn: sqlite3.Connection) -> None:
    ws = wb.create_sheet("Products")
    _write_title(ws, "A1", "Top Products by Revenue")
    rows = top_listings_by_revenue(conn, limit=50)
    _write_table(
        ws,
        start_row=3,
        headers=["Listing ID", "Item Name", "Revenue", "Units", "Orders"],
        rows=[
            [
                r["listing_id"],
                r["item_name"] or "",
                round(r["revenue"], 2),
                r["units"],
                r["orders"],
            ]
            for r in rows
        ],
    )


def _sheet_countries(wb: Workbook, conn: sqlite3.Connection) -> None:
    ws = wb.create_sheet("Countries")
    _write_title(ws, "A1", "Revenue by Country")
    rows = revenue_by_country(conn)
    _write_table(
        ws,
        start_row=3,
        headers=["Country", "Revenue", "Orders"],
        rows=[[r["country"], round(r["revenue"], 2), r["orders"]] for r in rows],
    )


def _sheet_data_quality(wb: Workbook, conn: sqlite3.Connection) -> None:
    ws = wb.create_sheet("Data Quality")
    _write_title(ws, "A1", "Data Quality Issues")
    rows = issues_repo.list_issues(conn, limit=1000)
    _write_table(
        ws,
        start_row=3,
        headers=["Severity", "Check", "Table", "Row Ref", "Message"],
        rows=[
            [
                r["severity"],
                r["check_name"],
                r["table_name"] or "",
                r["row_ref"] or "",
                r["message"],
            ]
            for r in rows
        ],
    )


def _sheet_insights(wb: Workbook, conn: sqlite3.Connection) -> None:
    ws = wb.create_sheet("Insights")
    _write_title(ws, "A1", "Business Insights")
    findings = generate_insights(conn)
    _write_table(
        ws,
        start_row=3,
        headers=["Severity", "Title", "Detail"],
        rows=[[f.severity.value, f.title, f.detail] for f in findings],
    )


# ---------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------

def build_report(
    conn: sqlite3.Connection,
    output_path: Path | str,
    run_reconciliation: bool = False,
) -> Path:
    """Build the Excel report and write it to output_path.

    Args:
        conn: an open SQLite connection.
        output_path: destination .xlsx path.
        run_reconciliation: if True, run reconciliation checks first
            so that their findings appear in the Data Quality sheet.

    Returns:
        The resolved output path.
    """
    output = Path(output_path)
    if run_reconciliation:
        reconciliation.run_all_checks(conn)

    wb = Workbook()
    _sheet_summary(wb, conn)
    _sheet_sales(wb, conn)
    _sheet_products(wb, conn)
    _sheet_countries(wb, conn)
    _sheet_data_quality(wb, conn)
    _sheet_insights(wb, conn)

    output.parent.mkdir(parents=True, exist_ok=True)
    wb.save(output)
    return output